language: python
cache: pip
python:
  # see https://docs.travis-ci.com/user/languages/python/ for options
  - "2.7" # hypothesis's minimum version for 2.x
  - "3.3" # hypothesis's minimum version for 3.x
  - "3.4" # trusty
  - "3.5" # >= xenial
  - "3.6-dev"
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
# command to run tests
script:
  - "python -m pytest tests/ *.py -v --doctest-modules"
notifications:
  email: false
